# Nginx alternative to deploy/Caddyfile
server {
    listen 80;
    listen [::]:80;
    server_name obsidianNotes.piersonl.com;

    root /var/www/obsidianNotes/public;
    index index.html;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
